### PR TITLE
#91: Gridding the blogz.

### PR DESCRIPTION
**Pull request by serundeputy**

### CODE REVIEW

**Comment by pirog** [comment]
@serundeputy def looking better. I think we def want to have the vertical lines, and maybe switch to a two column grid so its not looking so scrunched a la

screen shot 2018-01-06 at 10 41 29 am

**Comment by serundeputy** [comment]
Will do

**Comment by reynoldsalec** [comment]
Was playing with this and think doing a thicker line makes the vertical lines not necessary:

screen shot 2018-01-07 at 9 48 10 pm

If we're going to do the vertical lines, we'll want to close the space between each piece of the grid:

screen shot 2018-01-07 at 9 49 35 pm

**Comment by serundeputy** [comment]
Thanks @reynoldsalec i've pushed up a version with thicker horizontal rule and sans vertical bar.

let me know what you think! https://pr-92-zfngtwa-femv4bu3mqicm.us.platform.sh/blog/

**Comment by pirog** [comment]
Let’s talk about this in our meeting so we can all get on the same page
about what we actually want this to look like!

**Comment by serundeputy** [comment]
@pirog @reynoldsalec here is a 2x2 grid more squarified w/ vertical bars: https://pr-92-zfngtwa-femv4bu3mqicm.us.platform.sh/blog/3/index.html

**Comment by pirog** [comment]
@serundeputy looking good! Maybe drop in some extra top padding so the top padding = bottom padding and i think we will be good to go

**Comment by serundeputy** [comment]
@pirog added some padding to the top of each blog grid. https://pr-92-zfngtwa-femv4bu3mqicm.us.platform.sh/blog/

**Comment by pirog** [comment]
@serundeputy nice although now we are not centered anymore :( Going to drop in some centering padding bottom

**Comment by pirog** [comment]
also god bless the github built in text editor

**Comment by pirog** [comment]
merge minotaur engaged

**Pull request merged**
